In [1]:
print(1+2)


3


In [4]:
a='I am in School'
print(a)
type(a)

I am in School


str

In [6]:
import numpy as np                                              #Creating Arrays from Python list
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [7]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [10]:
np.array([range(i,i+3) for i in (5,7,9)])

array([[ 5,  6,  7],
       [ 7,  8,  9],
       [ 9, 10, 11]])

In [11]:
                                                                 #Creating Arrays from Scratch 

                                                                 #Create a length(10) integer array filled with zeros
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.zeros(3,3, dtype='int')

TypeError: data type not understood

In [13]:
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [14]:
np.ones(9, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [15]:
np.ones((4,1), dtype=int)

array([[1],
       [1],
       [1],
       [1]])

In [17]:
np.ones((2,2), dtype=int)

array([[1, 1],
       [1, 1]])

In [18]:
np.full((2,2), 3.5)

array([[3.5, 3.5],
       [3.5, 3.5]])

In [20]:
np.arange(0,30,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [4]:
import numpy as np


In [7]:
np.linspace(1,10,.5)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: object of type <class 'float'> cannot be safely interpreted as an integer.
  """Entry point for launching an IPython kernel.


array([], dtype=float64)

In [6]:
np.random.random((3,3))                            # Create a 3x3 array of uniformly distributed
                                                   # random values between 0 and 1

array([[0.48433022, 0.1294893 , 0.11065664],
       [0.97371468, 0.24119226, 0.62637666],
       [0.23638996, 0.27102449, 0.20816901]])

In [10]:
np.random.normal(0,1,(3,3))                       #Create a 3x3 array of normally distributed random values
                                                  #With mean 0 and standard deviation 1

array([[ 1.32801426, -0.9140731 , -0.89358398],
       [ 1.44643571,  0.84017195, -0.35383554],
       [ 0.89200659, -0.90500906,  1.00041557]])

In [13]:
np.random.randint(0,10,(3,3))                    # Create a 3x3 array of random integers in the interval [0, 10)

array([[9, 7, 3],
       [0, 5, 6],
       [5, 7, 4]])

In [14]:
np.eye(3)                                        # 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [16]:
np.eye(1)

array([[1.]])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.empty(3)                                       #Create an uninitialized array of three integers
                                                  #The values will be whatever happens to already exist at that memory location

array([1., 1., 1.])

In [19]:
np.empty(2)

array([5.43230922e-312, 7.29112202e-304])

In [20]:
np.empty(1)

array([7.29112202e-304])

In [21]:
np.empty(4)

array([1., 1., 1., 1.])