In [1]:
#Data Manipulation using NumPy Arrays
#Manipulation of NumPy arrays to access data and subarrays, and to split, reshape, and join arrays.

#Attributes of Arrays: Determining the size, shape, memory consuption, and data types of arrays.
#Indexing of Arrays: Getting and setting the value of individual array elements.
#Slicing of Arrays: Getting and setting smaller subarrays within a larger array.
#Reshaping of Arrays: Changing the shape of a given array.
#Joining and Splitting of Arrays: Combining multiple arrays into one, and spilliting one array into many. 

In [1]:
#Attributes of Arrays:


In [1]:
import numpy as np
np.random.seed(0)                              #Seed for Reproducibility

In [3]:
x1 = np.random.randint(10, size=6)            #One-Dimensional Array
print("x1 ndim: ", x1.ndim)                    #ndim is number of dimension
print("x1 shape: ", x1.shape)                  #shape is the size of each dimension
print("x1 size: ", x1.size)                    #size is total size of the array
print("dtype: ", x1.dtype)                     #dtype is data type of the array
print("itemsize:", x1.itemsize, "bytes")       #itemsize lists the size in bytes of each array element
print("nbytes:", x1.nbytes, "bytes")           #nbytes lists the total size in bytes of the array

#Note: It is expected that the nbytes is equal to the itemsize times size. 

x1 ndim:  1
x1 shape:  (6,)
x1 size:  6
dtype:  int32
itemsize: 4 bytes
nbytes: 24 bytes


In [6]:
x2 = np.random.randint(10, size=(3,4))          #Two-Dimensional Array

In [7]:
x3 = np.random.randint(10, size=(3,4,5))        #Three-Dimensional Array

In [13]:
#Indexing of Arrays:

In [14]:
x1                                              #One- Dimensional Array

array([2, 3, 8, 1, 3, 3])

In [18]:
x1[0]                                           #Indexing begins from 0,beginning from Left hand side

2

In [20]:
x1[5]

3

In [21]:
x1[-1]                                         #Negative Indexing begins from Right Hand Side from -1

3

In [22]:
x1[-6]

2

In [26]:
x2                                            #Two-Dimesnsional Array

array([[3, 7, 0, 1],
       [9, 9, 0, 4],
       [7, 3, 2, 7]])

In [27]:
x2[0,0]

3

In [28]:
x2[0,1]

7

In [29]:
x2[0,2]

0

In [30]:
x2[0,3]

1

In [31]:
x2[1,1]

9

In [32]:
x2[2,2]

2

In [33]:
#Modification in any of the above indexation
x2[0,0] = 12
x2

array([[12,  7,  0,  1],
       [ 9,  9,  0,  4],
       [ 7,  3,  2,  7]])

In [35]:
x2[1,0] = 1
x2

array([[12,  7,  0, 14],
       [ 1,  9,  0,  4],
       [ 7,  3,  2,  7]])

In [36]:
#Slicing of Arrays, Accessing Subarrays: Numpy slicing syntax  x[start:stop:step], if they aren't mentioned, then,
#default values are taken as start=0, stop=size of dimension, step=1.

In [40]:
#One-Dimensional Sub-Arrays
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
x[:5]                             #First 5 elements.

array([0, 1, 2, 3, 4])

In [42]:
x[5:]                             #Elements after index 5

array([ 5,  6,  7,  8,  9, 10, 11])

In [44]:
x[4:6]                           #Middle Sub-Array

array([4, 5])

In [45]:
x[5:8]

array([5, 6, 7])

In [46]:
x[::2]                           #Every Other Element

array([ 0,  2,  4,  6,  8, 10])

In [47]:
x[::1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [48]:
x[1::2]                          #Every Other Element, Starting at Index 1

array([ 1,  3,  5,  7,  9, 11])

In [49]:
x[0::2]

array([ 0,  2,  4,  6,  8, 10])

In [50]:
x[1::1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [51]:
x[0::1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [52]:
#Reversing An Array, All elements reveresed 
x[::-1]     

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [53]:
#Reversing An Array after index 5
x[5::-2]

array([5, 3, 1])

In [55]:
x[4::-1]

array([4, 3, 2, 1, 0])

In [56]:
#Multidimensional Subarrays
x2

array([[12,  7,  0, 14],
       [ 1,  9,  0,  4],
       [ 7,  3,  2,  7]])

In [57]:
x2[:2,:3]                           #Two Rows, Three Columns

array([[12,  7,  0],
       [ 1,  9,  0]])

In [58]:
x2[:1,:2]

array([[12,  7]])

In [59]:
x2[:3,:1]

array([[12],
       [ 1],
       [ 7]])

In [60]:
x2[:2,:2]

array([[12,  7],
       [ 1,  9]])

In [61]:
x2[:1,:1]

array([[12]])

In [62]:
#Subarray Dimensions can be Reveresed Together. 
x2[::-1,::-1]

array([[ 7,  2,  3,  7],
       [ 4,  0,  9,  1],
       [14,  0,  7, 12]])

In [63]:
x3

array([[[2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1],
        [4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6]],

       [[7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4],
        [4, 3, 4, 4, 8],
        [4, 3, 7, 5, 5]],

       [[0, 1, 5, 9, 3],
        [0, 5, 0, 1, 2],
        [4, 2, 0, 3, 2],
        [0, 7, 5, 9, 0]]])

In [65]:
#Accessing a Single Row or Column of an Array: Can be done by combining indexing and slicing.
#Using an empty slice marked by a colon(:)
print(x2[:,0])                           #First Column of X2

[12  1  7]


In [66]:
print(x2[0,:])                           #First Row of X2

[12  7  0 14]


In [67]:
print(x2[0])                            #Equivalent to print(x2[0,:])

[12  7  0 14]


In [7]:
#Subarrays as no-copy views: Array Slices return views and not copies of Array Data.This default behaviour is useful
#As when working on a large dataset, one can access and process pieces of the dataset without copying the buffer data.

#Note: Values of X2 are different because I worked on it the next day. 
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [9]:
X2_sub = x2[:2,:2]                    #Extracting 2x2 Subarray
print(X2_sub)

[[3 5]
 [7 6]]


In [10]:
#When we modify this subarray, the original array is changed.
X2_sub[0,0] = 31
print(X2_sub)

[[31  5]
 [ 7  6]]


In [11]:
print(x2)

[[31  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [12]:
#Creating Copies of Arrays: When we need to explicitly copy the data within an array or a subarray, copy() method is used.
#Using copy() helps us to make no changes in the orriginal array.
X2_sub_copy = x2[:2,:2].copy()
print(X2_sub_copy)

[[31  5]
 [ 7  6]]


In [13]:
X2_sub_copy[0,0] = 42
print(X2_sub_copy)

[[42  5]
 [ 7  6]]


In [14]:
print(x2)

[[31  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [15]:
#Reshaping of Arrays: reshape() method is used.
#For eg, When numbers from 1 to 9 are to be put in a 3x3 grid, then the following can be done.

grid = np.arange(1,10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
#Another way of reshaping pattern is the conversion of a one-dimensional array into two-dimensional matrix.
#This can be done with reshape method or using newaxis keyword within a slice operation.
#Note: reshape((row,column))

x=np.array([1,2,3])              #Row Vector via Reshape
x.reshape((1,3))

array([[1, 2, 3]])

In [25]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [26]:
x.reshape((3,1))                 #Convert to Column Matrix using reshape

array([[1],
       [2],
       [3]])

In [27]:
x[:, np.newaxis]                #Convert to Column Matrix using newaxis

array([[1],
       [2],
       [3]])

In [28]:
#Joining and Splitting of Arrays: Multiple Arrays can be combined into one or single array can be split into multiple arrays.

#Concatenation of Arrays: Joining of two arrays in NumPy can be done by using np.concatenate,np.vstack and np.hstack.

x=np.array([1,2,3])
y=np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [29]:
z=np.array([99,99,99])                       #Concatenate More than 2 array
print(np.concatenate([x,y,z]))

[ 1  2  3  3  2  1 99 99 99]


In [30]:
#For Two-Dimensional Array: Concatenate around first axis
grid = np.array([[1,2,3],
                  [4,5,6]])
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [31]:
#Concatenate around second axis(zero-indexed)

np.concatenate([grid,grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [32]:
#Working with arrays of mixed dimensions: np.vstack is used for vertical stack and np.hstack is used for horizontal stack.
x=np.array([1,2,3])
grid=np.array([[9,8,7],
               [6,5,4]])
np.vstack([x,grid])                     #Vertically Stacked the Array

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [33]:
y=np.array([[99],
            [99]])
np.hstack([grid,y])                     #Horizontally Stacked the Array

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [35]:
np.hstack([y,grid])

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

In [37]:
np.vstack([grid,x])

array([[9, 8, 7],
       [6, 5, 4],
       [1, 2, 3]])

In [44]:
z=np.array([31,31,31])
np.dstack([x,z])                           #Stack arrays along the third axis

array([[[ 1, 31],
        [ 2, 31],
        [ 3, 31]]])

In [9]:
#Splitting of Array: Functions that are used are np.split, np.hsplit and np.vsplit. 

#Note: In The output, N split points leads to N+1 SubArrays. 

x=([1,2,3,99,99,3,2,1])
x1,x2,x3=np.split(x,[3,5])
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [10]:
grid= np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
upper,lower=np.vsplit(grid,[2])                   #Vertical Splitting
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [12]:
left,right=np.hsplit(grid,[2])                     #Horizontal Spiltting
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [ ]:
#np.dsplit can also be used similarly.