In [6]:
#NumPy Universal Functions: Vectorized operations in NumPy are implemented by ufuncs. Ufuncs are extremely flexible.
#Ufuncs can exist in two ways: unary ufuncs(operate on single input) & binary ufuncs(operate on two inputs).

#1: Array Arithmetic
import numpy as np
np.random.seed(0)

x=np.arange(4)
print("x  =",x)
print("x+5=",x+5)                  #Addition or np.add
print("x+10=",x+10)
np.add(x,5)
np.add(x,10)
print("x-5=",x-5)                  #Subtration or np.subtract
print("x-31=",x-31)
np.subtract(x,5)
np.subtract(x,-31)
print("x*3=",x*3)                  #Multiplication or np.multiply
print("x*2=",x*2)
np.multiply(x,3)
np.multiply(x,2)
print("x/2=",x/2)                  #Division or np.divide
np.divide(x,2)
print("x//2=",x//2)                #Floor Division or np.floor_divide
np.floor_divide(x,2)

x  = [0 1 2 3]
x+5= [5 6 7 8]
x+10= [10 11 12 13]
x-5= [-5 -4 -3 -2]
x-31= [-31 -30 -29 -28]
x*3= [0 3 6 9]
x*2= [0 2 4 6]
x/2= [0.  0.5 1.  1.5]
x//2= [0 0 1 1]


array([0, 0, 1, 1], dtype=int32)

In [10]:
#Negation can be done using a negative sign(-) or np.negative
#Exponentiation can be done by using ** operator or np.power
#Modulus/Remainder can be found by using % operator or np.mod 

print("-x =",-x)
np.negative(1)
print("x**2=",x**2)
np.power(x,2)
print("x**3=",x**3)
np.power(x,3)
print("x%2=",x%2)
np.mod(x,2)
print("x%3=",x%3)
np.mod(x,3)
print("x%-2=",x%-2)
np.mod(x,-2)

-x = [ 0 -1 -2 -3]
x**2= [0 1 4 9]
x**3= [ 0  1  8 27]
x%2= [0 1 0 1]
x%3= [0 1 2 0]
x%-2= [ 0 -1  0 -1]


array([ 0, -1,  0, -1], dtype=int32)

In [11]:
#2: Absolute Value: Use abs() or np.absolute() or np.abs()

x=np.array([-2,-1,0,1,2])
abs(x)

array([2, 1, 0, 1, 2])

In [13]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [14]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [15]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

In [16]:
#3: Trignometric Functions: 
#Defining an array of angles:

theta=np.linspace(0,np.pi,3)

In [18]:
#Computing trignometric functions on these values:

print("theta =", theta)
print("sin(theta)=",np.sin(theta))
print("cos(theta)=",np.cos(theta))
print("tan(theta)=",np.tan(theta))

theta = [0.         1.57079633 3.14159265]
sin(theta)= [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta)= [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta)= [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [19]:
#Inverse trigonometric functions: Use arcsin(),arccos(), arctan()

x=[-1,0,1]
print("x  =",x)
print("arcsin(x)=", np.arcsin(x))
print("arccos(x)=", np.arccos(x))
print("arctan(x)=", np.arctan(x))

x  = [-1, 0, 1]
arcsin(x)= [-1.57079633  0.          1.57079633]
arccos(x)= [3.14159265 1.57079633 0.        ]
arctan(x)= [-0.78539816  0.          0.78539816]


In [21]:
#4: Exponents & Logarithms:
#For Exponentials:

x=[1,2,3]
print("x   =",x)
print("e^x =",np.exp(x))           #e raised to the power of the values in array
print("2^x =",np.exp2(x))          
print("3^x =",np.power(3,x))       

x   = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]


In [22]:
#For Logarithms: Inverse of Exponentials are Logarithms. 
#np.log() gives natural logarithm 
#np.log2() gives Base-2 Logarithm
#np.log10() gives Base-10 Logaritm

x=[1,2,4,10]
print("x   =",x)
print("ln(x)  =", np.log(x))
print("log2(x)   =", np.log2(x))
print("log10(x)  =", np.log10(x))

x   = [1, 2, 4, 10]
ln(x)  = [0.         0.69314718 1.38629436 2.30258509]
log2(x)   = [0.         1.         2.         3.32192809]
log10(x)  = [0.         0.30103    0.60205999 1.        ]


In [23]:
#More precision with very small input:

x=[0, 0.001, 0.01, .1]
print("exp(x)-1=", np.expm1(x))
print("log(1+x)=", np.log1p(x))

exp(x)-1= [0.         0.0010005  0.01005017 0.10517092]
log(1+x)= [0.         0.0009995  0.00995033 0.09531018]


In [24]:
#Specialized ufuncs: Specialized and obscure ufuncs is the submodule scipy.special.

from scipy import special